New xep 313 mam2
fritzy/SleekXMPP pull request #456
Opened 2017-06-05 17:28 UTC by mariohock

As discussed in sleek@conference.jabber.org, here the pull request that updates the "XEP-0313 Message Archive Management" plugin from "urn:xmpp:mam:tmp" to "urn:xmpp:mam:2".

2017-06-06 07:58 UTC, linkmauve requested changes
I haven’t tested, but overall this is a very nice improvement over the existing code, thanks!

2017-06-06 07:58 UTC, linkmauve commented on examples/echo_client_with_mam.py
> +    xmpp.register_plugin('xep_0060') # PubSub
This should probably not be loaded at all.

2017-06-06 07:58 UTC, linkmauve commented on examples/echo_client_with_mam.py
> +    xmpp.register_plugin("xep_0004") # Data Form (required by xep_0313)
This one is already loaded on line 166.

2017-06-06 07:58 UTC, linkmauve commented on examples/echo_client_with_mam.py
> +            if ( msg["body"] ):
By convention, if conditions don’t generally use parentheses.

2017-06-06 07:58 UTC, linkmauve commented on examples/echo_client_with_mam.py
> +                print( "From:", msg["from"] )
PEP-0008 recommends to not put spaces inside of parentheses, same for the next four lines.

2017-06-06 07:58 UTC, linkmauve commented on examples/echo_client_with_mam.py
> +                    help="password to use")
Maybe add some more options, for example to query only a certain range, either by stanza-id, by date, or just ignore that comment. ^^

2017-06-06 07:58 UTC, linkmauve commented on examples/echo_client_with_mam.py
> +                  2017  Mario Hock
The convention is generally to write “Copyright (C)” again on every line.

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/mam.py
> +        if ( number_of_queried_elements ):
Same here and below, no parentheses in if condition.

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/mam.py
> +                 timeout=None, callback=None, number_of_queried_elements=None, collect_all=True):
The last two arguments should probably go before timeout and callback.

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/mam.py
> +            iq['mam']['rsm']['max'] = str(number_of_queried_elements)
It would make sense to modify the rsm plugin to automatically convert to and from ints, see sleekxmpp/plugins/xep_0047/stanza.py for an example.

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/mam.py
> +        self._open_queries = dict()
Use {} instead of dict().

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/mam.py
> +                 timeout=None, callback=None, number_of_queried_elements=None, collect_all=True):
Same here, arguments timeout and callback should probably stay at the end of the argument list. Also maybe add a block argument for consistency?

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/stanza.py
> +        #return xep_0082.parse(timestamp)
You shouldn’t leave commented out code.

2017-06-06 07:58 UTC, linkmauve commented on sleekxmpp/plugins/xep_0313/stanza.py
> +        #return xep_0082.parse(timestamp)
Same here.

2017-06-10 15:46 UTC, mariohock commented
Thanks for your helpful feedback. I incorporated it and pushed it to my forked repository. (Hope I didn't miss anything.)

Is there a way to update the merge request to the new commit, or do I have to create a new merge request?

2017-06-10 15:49 UTC, mariohock commented on examples/echo_client_with_mam.py
> +                    help="password to use")
I thought about this, but I the think the example focuses on developers who want to get into the code and need a point to start. Therefore, having lots of options from a users perspective is no priority.

2017-06-11 16:59 UTC, mariohock commented
Actually, I did miss something -- the "block" command. Added it and pushed the changes.

2017-06-16 18:31 UTC, linkmauve commented
LGTM.

2017-06-23 18:35 UTC, mariohock commented
Great. :-)

Is there any action from me required? What are the next steps?

2017-08-07 01:12 UTC, merged